/* exported elements */

var elements =
{
    settings : {
        useCustomAutoplayFeature : true,
        disablePauseOnLostFocus : false,
        disableSlamStopOption: true,
        disableWinVisualCancellation: false,
        bigWinMul : 15,
        hugeWinMul : 25,
        megaWinMul : 50
    },
    infoBar : {
        balanceString: {
            value: 'Balance ',
            translations: {
                bg: 'Баланс ',
                cs: 'Zůstatek ',
                da: 'Saldo ',
                de: 'Guthaben ',
                el: 'Υπόλοιπο ',
                es: 'Saldo ',
                et: 'Kontoseis ',
                fi: 'Saldo ',
                fr: 'Solde ',
                hu: 'Egyenleg ',
                is: 'Staða ',
                it: 'Saldo ',
                ja: '残高 ',
                lt: 'Balansas ',
                lv: 'Atlikums ',
                nl: 'Saldo ',
                no: 'Saldo ',
                pl: 'Saldo ',
                pt: 'Saldo ',
                ro: 'Sold ',
                ru: 'Баланс ',
                sk: 'Zostatok ',
                sr: 'Stanje ',
                sv: 'Saldo ',
                th: 'ยอดเงินคงเหลือ ',
                tr: 'Bakiye ',
                zh: '资金 '
            }
        },
        totalBetString: {
            value: 'Total Bet ',
            translations: {
                bg: 'Общ залог ',
                cs: 'Celkový vklad ',
                da: 'Samlet Indsats ',
                de: 'Gesamteinsatz ',
                el: 'Συνολικό Ποντάρισμα ',
                es: 'Apuesta total ',
                et: 'Kogupanus ',
                fi: 'Kokonaispanos ',
                fr: 'Mise totale ',
                hu: 'Teljes tét ',
                is: 'Heildarveðmál ',
                it: 'Puntata totale ',
                ja: '合計ベット ',
                lt: 'Bendros lažybos ',
                lv: 'Kopējā likme ',
                nl: 'Totale inzet ',
                no: 'Total innsats ',
                pl: 'Całkowity zakład ',
                pt: 'Aposta Total ',
                ro: 'Miză totală ',
                ru: 'Общая ставка ',
                sk: 'Celková stávka ',
                sr: 'Ukupni ulog ',
                sv: 'Total insats ',
                th: 'เดิมพันรวม ',
                tr: 'Toplam Bahis ',
                zh: '总赌注 '
            }
        }
    },
    menuScreen : {
        wildDescriptionString : {
            value: 'A wild will expand across\nthe entire reel and\naward 1 free spin',
            translations: {
                bg: 'Уайлд символът се появява\nвърху целия барабан и дава\n1 безплатно завъртане.',
                cs: 'Symbol Wild se rozšíří po\ncelém válci a udělí\n1 volné točení.',
                da: 'Et wild udvider sig over\nhele hjulet, og giver\n1 gratis tur',
                de: 'Ein Wild breitet sich über die\nkomplette Walze aus und gewährt\n1 kostenlose Drehung.',
                el: 'Ένα σύμβολο wild θα επεκταθεί σε\nολόκληρο τον τροχό και θα προσφέρει\n1 δωρεάν περιστροφή.',
                es: 'Un wild se extenderá a\ntravés de todo el carrete y\ndará 1 giro gratis.',
                et: 'Wild laieneb üle\nkogu ketta ja annab\n1 tasuta spinni.',
                fi: 'Wild laajentuu koko\nrullalle ja antaa\n1 ilmaispyöräytyksen.',
                fr: 'Un symbole Wild se répandra\nsur le rouleau entier et\noctroiera 1 lancer gratuit.',
                hu: 'A jóker a teljes tárcsára\nkiterjed, és 1 ingyenes\npörgetést nyer vele.',
                is: 'Wild-tákn dreifist\nyfir allt hjólið og\nveitir 1 frísnúning.',
                it: 'Un Wild si estende sull\n\'intero rullo e garantisce\n1 giro gratuito.\'',
                ja: '"ワイルドはリール全体に影響し、\nフリースピンが\n1回与えられます。"',
                lt: 'Laukinis prasiplės per\nvisą ritę ir suteiks\n1 nemokamą suktuką.',
                lv: 'Wild simbols izpletīsies pa\nvisu cilindru un sniegs vienu\nbezmaksas griešanas reizi.',
                nl: 'Een wild breidt uit\nover de hele rol en geeft\n1 gratis draai.',
                no: 'Wild utvides til å dekke\nhele hjulet og gir\n1 gratisspinn.',
                pl: 'Symbol wild rozprzestrzenia\nsię na cały bęben i przyznaje\n1 bezpłatne zakręcenie.',
                pt: 'O símbolo Wild expande-se por\ntoda a janela para proporcionar\numa Rodada Grátis.',
                ro: 'Un simbol wild se va extinde\npe întreaga rolă și îți va\nacorda 1 rotire gratuită.',
                ru: 'Дикий символ распространяется\nна весь барабан и запускает\n1 бесплатный спин.',
                sk: 'Po celej dĺžke valca sa\nrozšíri symbol Wild, za ktorý\nzískate 1 bezplatné zatočenie.',
                sr: 'Džoker će se proširiti\nna ceo valjak i dodeliti\n1 besplatni obrtaj.',
                sv: 'En wildsymbol sträcker sig\növer hela hjulet och ger\n1 gratis-spin.',
                th: '"ไวลด์จะขยาย\nไปทั้งวงล้อ และ\nให้ 1 การหมุนฟรี"',
                tr: 'Wild semboller tüm\nmakaraya yayılır ve\n1 ücretsiz döndürme verir.',
                zh: '"百搭标志会扩散\n到整个轮盘，\n并奖励 1 次免费旋转。"'
            }
        },
        paywaysDescriptionString : {
            value: '3 like symbols pay\nanywhere on a\npay line',
            translations: {
                bg: '3 подобни символа се\nизплащат навсякъде\nвърху игровата линия',
                cs: '3 stejné symboly\nve výplatní\nřadě vyplácejí',
                da: '3 ens symboler giver\ngevinst hvor som helst\npå en betalingslinje',
                de: '3 gleiche Symbole auf\neiner Gewinnlinie\ngewinnen überall',
                el: '3 όμοια σύμβολα πληρώνουν\nοπουδήποτε και αν εμφανιστούν\nσε μια γραμμή πληρωμής',
                es: '3 símbolos iguales se\npagan en una línea de\npago en cualquier parte',
                et: '3 ühesugust sümbolit\nmaksavad sõltumata\nasukohast võiduliinil',
                fi: '3 samanlaista symbolia\nantavat voiton missä\ntahansa voittolinjalla',
                fr: '3 symboles identiques\nforment une\nligne gagnante',
                hu: 'Egy adott nyerősoron kipörgetett\n3 egyforma szimbólum mindig\nnyer, bárhol is legyenek',
                is: '3 eins tákn\ngreiða hvar sem\ner í vinningslínu.',
                it: '3 simboli uguali\nvincono ovunque su\nuna linea di vincita',
                ja: '"3のような形をしたシンボルは、\nペイライン上のどこで、\nも有効と見なされます"',
                lt: '3 "patinka" simboliai\ngrąžina pinigus bet\nkurioje mokėjimo linijoje',
                lv: '3 vienādi simboli\nizmaksā jebkur uz\nizmaksu rindas',
                nl: '3 dezelfde symbolen\nworden overal op een\nwinlijn uitbetaald',
                no: '3 like symboler gir\ngevinst hvor som helst\npå en gevinstlinje',
                pl: '3 takie same symbole w\ndowolnym miejscu linii\nwypłaty zapewniają wygraną',
                pt: '3 símbolos iguais\npagam em qualquer\nlinha de pagamento.',
                ro: 'Linia de plată se extinde pe\ntoate cele cinci role, dar\norice trei simboluri identice\nconsecutive plătesc un premiu',
                ru: '3 символа лайка приносят\nвыигрыш, появившись в любом\nместе на выигрышной линии',
                sk: 'Za 3 rovnaké symboly sa\nvypláca výhra, nech už sú\nkdekoľvek na výhernej línii',
                sr: '3 slična simbola isplaćuju\nse bilo gde na liniji\nza plaćanje',
                sv: '3 likadana symboler\nger utbetalning var som\nhelst på en insatsrad',
                th: '"สัญลักษณ์ที่ตรงกัน 3 ตัวที่ใดๆ\nจะได้รับรางวัลในแถวการจ่าย"',
                tr: 'Ödeme çizgisinin herhangi bir\nyerinde açılan 3 benzer\nsembol için ödeme yapılır',
                zh: '"赔付线任意位置上的 3 个\n同样的符号都可获奖"'
            }
        },
        clickToPlayString: {
            value: 'CLICK TO PLAY',
            translations: {
                bg: 'Натисни, за да играеш',
                cs: 'Kliknutím hrajte',
                da: 'Klik for at spille',
                de: 'Zum Spielen klicken',
                el: 'Κάντε κλικ για να παίξετε',
                es: 'Haz clic para jugar',
                et: 'Mängimiseks vajutage',
                fi: 'Napsauta pelataksesi',
                fr: 'Cliquer pour jouer',
                hu: 'A játék indításához kattintson ide',
                is: 'Smelltu til að leika',
                it: 'Clicca per giocare',
                ja: 'クリックしてプレイする',
                lt: 'Spausti, kad žaistum',
                lv: 'Klikšķināt, lai spēlētu.',
                nl: 'Klik om te spelen',
                no: 'Klikk for å spille',
                pl: 'Kliknij, aby grać',
                pt: 'Clica para continuar',
                ro: 'Dă clic pentru a juca',
                ru: 'Щелкните, чтобы начать игру',
                sk: 'Kliknutím spustíte hru',
                sr: 'Klikni za igru',
                sv: 'Klicka för att spela',
                th: 'คลิกเพื่อเล่น',
                tr: 'Oynamak için tıkla',
                zh: '点击进行游戏'
            }
        }
    },
    infoScreens: {
        sunwildPage : {
            headerString: {
                value: 'Sun Wild',
                translations: {
                    bg: 'Уайлд символ Слънце',
                    cs: 'Symbol Wild se sluncem',
                    da: 'Sol-wild',
                    de: 'Sonnen-Wild',
                    el: 'Σύμβολο Wild Ήλιος',
                    es: 'Wild sol',
                    et: 'Päikese Wild',
                    fi: 'Aurinko-Wild',
                    fr: 'Wild soleil',
                    hu: 'Nap jóker',
                    is: 'Sólar-Wild',
                    it: 'Wild Sole',
                    ja: '太陽のワイルド',
                    lt: '"Sun Wild"',
                    lv: 'Sun wild simbols',
                    nl: 'Zonnewild',
                    no: 'Sol-wild',
                    pl: 'Symbol wild słońca',
                    pt: 'Sol Wild',
                    ro: 'Simbol Wild soare',
                    ru: 'Дикий символ «Солнце»',
                    sk: 'Slnečný symbol Wild',
                    sr: 'Džoker Sunce',
                    sv: 'Sol-wildsymbol',
                    th: 'ไวลด์พระอาทิตย์',
                    tr: 'Güneş Wild Sembolü',
                    zh: '百搭太阳'
                }
            },
            line1String: {
                value: 'Present on all reels and substitutes for all symbols',
                translations: {
                    bg: 'Появява се върху всички барабани и замества всички символи',
                    cs: 'Nachází se na všech válcích a nahrazuje všechny symboly',
                    da: 'Findes på alle hjul, og kan erstatte alle symboler.',
                    de: 'Auf allen Walzen präsent und ersetzt alle Symbole',
                    el: 'Εμφανίζεται σε όλους τους τροχούς και αντικαθιστά όλα τα σύμβολα',
                    es: 'Está presente en todos los carretes y sustituye a todos los símbolos',
                    et: 'On kõikidel ketastel ja asendab kõiki sümboleid',
                    fi: 'Olemassa kaikilla rullilla ja korvaa kaikki symbolit',
                    fr: 'Présents sur tous les rouleaux et remplacent tous les symboles',
                    hu: 'Minden tárcsán szerepel, és minden szimbólumot helyettesít',
                    is: 'Til staðar á öllum hjólum og kemur í stað allra tákna',
                    it: 'È presente su tutti i rulli e sostituisce qualunque simbolo',
                    ja: '"すべてのリールに出現可能ですべてのシンボルの代用になります"',
                    lt: 'Pristatyta ant visų ričių ir visų simbolių pakeitimų',
                    lv: 'Redzams uz visiem cilindriem un aizvieto visus simbolus',
                    nl: 'Aanwezig op alle rollen en vervangt alle symbolen',
                    no: 'Finnes på alle hjul og erstatter alle symboler',
                    pl: 'Obecny na wszystkich bębnach; zastępuje wszystkie symbole',
                    pt: 'Presente em todas as janelas e substitui todos os símbolos.',
                    ro: 'Apare pe toate rolele și înlocuiește toate simbolurile',
                    ru: 'Появляется на всех барабанах и заменяет любой символ',
                    sk: 'Nachádza sa na všetkých valcoch a nahrádza všetky symboly',
                    sr: 'Prisutan na svim valjcima i zamena za sve simbole',
                    sv: 'Finns på alla hjul och ersätter alla symboler',
                    th: '"ปรากฏในทุกวงล้อ และ จะแทนที่ทุกสัญลักษณ์"',
                    tr: 'Tüm makaralarda bulunur ve tüm sembollerin yerine geçer',
                    zh: '"会在所有轮盘上显示可替代所有标记"'
                }
            },
            line2String: {
                value: 'Expands across entire reel and holds over',
                translations: {
                    bg: 'Появява се върху целия барабан и се задържа',
                    cs: 'Stabilně se rozšíří na celý válec',
                    da: 'Udvides over hele hjulet og gemmes',
                    de: 'Breitet sich über die komplette Walze aus und hält an',
                    el: 'Επεκτείνεται σε ολόκληρο τον τροχό και παραμένει σταθερό',
                    es: 'Se extiende a través de todo el carrete y se mantiene',
                    et: 'Laieneb üle kogu ketta ja jääb püsima',
                    fi: 'Laajentuu koko rullalle ja säilyy',
                    fr: 'Se répand sur tout le rouleau et y reste',
                    hu: 'A teljes tárcsára kiterjed és megmarad',
                    is: 'Dreifist yfir allt hjólið og heldur yfir',
                    it: 'Si estende sull\'intero rullo e rimane bloccato\'',
                    ja: '"リール全体に 影響します"',
                    lt: 'Plečiasi visoje ritėje ir tęsiasi',
                    lv: 'Izplešas pa visu cilindru un noturas uz tā',
                    nl: 'Breidt uit over de hele rol en blijft staan',
                    no: 'Utvides til å dekke hele hjulet og beholdes',
                    pl: 'Rozprzestrzenia się na cały bęben i pozostaje na miejscu',
                    pt: 'Expande-se por toda a janela e mantém-se.',
                    ro: 'Se extinde pe întreaga rolă și își menține poziția',
                    ru: 'Распространяется на весь барабан и не исчезает',
                    sk: 'Rozšíri sa na celú dĺžku valca a zostane tam',
                    sr: 'Širi se po celom valjku i drži preko',
                    sv: 'Sträcker sig över alla hjul och hålls kvar',
                    th: '"ขยายไปเต็มวงล้อ และตรึงอยู่ที่เดิม"',
                    tr: 'Tüm makaraya yayılır ve olduğu yerde kalır',
                    zh: '"会扩散至整个轮盘，并固定"'
                }
            },
            line3String: {
                value : 'Awards 1 free spin',
                translations: {
                    bg: 'Дава 1 безплатно завъртане',
                    cs: 'Udělí 1 volné točení',
                    da: 'Tildeler 1 gratis tur',
                    de: 'Gewährt 1 Gratis-Spin',
                    el: 'Δίνει 1 Δωρεάν Περιστροφή',
                    es: 'Da 1 giro gratis',
                    et: 'Annab 1 tasuta spinni',
                    fi: 'Saat 1 ilmaispyöräytyksen',
                    fr: 'Confère 1 lancer gratuit',
                    hu: '1 ingyenes pörgetés',
                    is: 'Veitir 1 frísnúning',
                    it: 'Conferisce 1 Giro Gratuito',
                    ja: '無料スピン1回獲得',
                    lt: 'Apdovanojama 1 nemokamu suktuku',
                    lv: 'Piešķir 1 bezmaksas griezienu',
                    nl: 'Levert 1 gratis draai op',
                    no: 'Gir 1 gratisspinn',
                    pl: 'Daje 1 bezpłatne zakręcenie',
                    pt: 'Atribui 1 Rodada Grátis',
                    ro: 'Acordă 1 rotire gratuită',
                    ru: '1 бесплатный спин в награду',
                    sk: 'Získate 1 bezplatné zatočenie',
                    sr: 'Dodeljuje 1 besplatni obrtaj',
                    sv: 'Ger 1 gratis-spin',
                    th: 'ได้ 1 ฟรีสปิน',
                    tr: '1 Ücretsiz Döndürme Verir',
                    zh: '奖励 1 次免费旋转'
                }
            }
        },
        paytablePage: {
            headerString: {
                value: 'Pay Table',
                translations: {
                    bg: 'Таблица на плащанията',
                    cs: 'Výplatní tabulka',
                    da: 'Udbetalingsrække',
                    de: 'Auszahlungstabelle',
                    el: 'Πίνακας Αποδόσεων',
                    es: 'Tabla de pagos',
                    et: 'Väljamaksete tabel',
                    fi: 'Maksutaulukko',
                    fr: 'Table de paiement',
                    hu: 'Kifizetési táblázat',
                    is: 'Greiðslutafla',
                    it: 'Tabella dei pagamenti',
                    ja: 'ペイテーブル',
                    lt: 'Mokėjimų lentelė',
                    lv: 'Izmaksu tabula',
                    nl: 'Uitbetalingstabel',
                    no: 'Utbetalingstabell',
                    pl: 'Tabela wypłat',
                    pt: 'Tabela de pagamentos',
                    ro: 'Tabel de plăți',
                    ru: 'Таблица выплат',
                    sk: 'Výherná tabuľka',
                    sr: 'Tabela za plaćanje',
                    sv: 'Vinsttabell',
                    th: 'ตารางการจ่าย',
                    tr: 'Ödeme Masası',
                    zh: '出彩表'
                }
            },
            allWinsPayString: {
                value : 'All wins pay',
                translations: {
                    bg: 'Всички печалби се изплащат',
                    cs: 'Všechny výhry vyplácejí',
                    da: 'Alle gevinster udbetales',
                    de: 'Alle Gewinne werden ausgezahlt',
                    el: 'Όλες οι νίκες πληρώνουν',
                    es: 'Todas las ganancias se pagan',
                    et: 'Kõik võidud tasuvad',
                    fi: 'Kaikki voitot maksetaan',
                    fr: 'Tous les gains rapportent',
                    hu: 'Minden nyeremény fizet',
                    is: 'Allir vinningar greiða',
                    it: 'Tutte le vincite pagano',
                    ja: '全ての獲得金が支払われます',
                    lt: 'Visų laimėjimų mokėjimas',
                    lv: 'Izmaksāti tiek visi laimesti.',
                    nl: 'Alle winsten betalen uit',
                    no: 'Alle gevinster gir utbetaling',
                    pl: 'Wszystkie wygrane są wypłacane',
                    pt: 'Todos os prémios dão origem a pagamento',
                    ro: 'Toate câștigurile se plătesc',
                    ru: 'Все выигрыши выплачиваются',
                    sk: 'Vyplácajú sa všetky výhry',
                    sr: 'Svi dobitci se isplaćuju',
                    sv: 'Alla vinster ger betalt',
                    th: 'จะมีการจ่ายให้ทุกรางวัล',
                    tr: 'Tüm kazançlar ödenir',
                    zh: '全胜赔付'
                }
            }
        },
        paylinesPage: {
            headerString: {
                value : 'Pay Lines',
                translations: {
                    bg: 'Игрови линии',
                    cs: 'Výplatní řady',
                    da: 'Udbetalingslinjer',
                    de: 'Gewinnlinien',
                    el: 'Γραμμές Πληρωμής',
                    es: 'Líneas de pago',
                    et: 'Võiduliinid',
                    fi: 'Maksulinjat',
                    fr: 'Lignes de paiement',
                    hu: 'Nyerősorok',
                    is: 'Vinningslínur',
                    it: 'Linee di pagamento',
                    ja: 'ペイライン',
                    lt: 'Mokėjimo linijos',
                    lv: 'Izmaksu rindas',
                    nl: 'Winlijnen',
                    no: 'Gevinstlinjer',
                    pl: 'Linie wypłaty',
                    pt: 'Linhas de pagamento',
                    ro: 'Linii de plată',
                    ru: 'Выигрышные линии',
                    sk: 'Výherné línie',
                    sr: 'Linije za plaćanje',
                    sv: 'Insatsrader',
                    th: 'แถวการจ่าย',
                    tr: 'Ödeme Çizgileri',
                    zh: '赔付线'
                }
            },
            paywaysString: {
                value : '3 like symbols pay anywhere on pay line',
                styles : {
                    el: { font: '18px arial' },
                    hu: { font: '18px arial' },
                    ja: { font: '18px arial' },
                    pl: { font: '18px arial' },
                    ro: { font: '18px arial' },
                    ru: { font: '18px arial' },
                    sk: { font: '18px arial' },
                    tr: { font: '18px arial' }
                },
                translations: {
                    bg: '3 подобни символа се изплащат навсякъде върху игровата линия',
                    cs: '3 stejné symboly ve výplatní řadě vyplácejí',
                    da: '3 ens symboler giver gevinst hvor som helst på en betalingslinje',
                    de: '3 gleiche Symbole auf einer Gewinnlinie gewinnen überall',
                    el: '3 όμοια σύμβολα πληρώνουν οπουδήποτε και αν\nεμφανιστούν σε μια γραμμή πληρωμής',
                    es: '3 símbolos iguales se pagan en una línea de pago en cualquier parte',
                    et: '3 ühesugust sümbolit maksavad sõltumata asukohast võiduliinil',
                    fi: '3 samanlaista symbolia antavat voiton missä tahansa voittolinjalla',
                    fr: '3 symboles identiques forment une ligne gagnante',
                    hu: 'Egy adott nyerősoron kipörgetett 3 egyforma szimbólum mindig nyer,\nbárhol is legyenek',
                    is: '3 eins tákn greiða hvar sem er í vinningslínu.',
                    it: '3 simboli uguali vincono ovunque su una linea di vincita',
                    ja: '"3のような形をしたシンボルは、\nペイライン上のどこでも有効と見なされます"',
                    lt: '3 "patinka" simboliai grąžina pinigus bet kurioje mokėjimo linijoje',
                    lv: '3 vienādi simboli izmaksā jebkur uz izmaksu rindas',
                    nl: '3 dezelfde symbolen worden overal op een winlijn uitbetaald',
                    no: '3 like symboler gir gevinst hvor som helst på en gevinstlinje',
                    pl: '3 takie same symbole w dowolnym miejscu linii\nwypłaty zapewniają wygraną',
                    pt: '3 símbolos iguais pagam em qualquer linha de pagamento.',
                    ro: 'Linia de plată se extinde pe toate cele cinci role,\ndar orice trei simboluri identice consecutive plătesc un premiu',
                    ru: '3 символа лайка приносят выигрыш,\nпоявившись в любом месте на выигрышной линии',
                    sk: 'Za 3 rovnaké symboly sa vypláca výhra,\nnech už sú kdekoľvek na výhernej línii',
                    sr: '3 slična simbola isplaćuju se bilo gde na liniji za plaćanje',
                    sv: '3 likadana symboler ger utbetalning var som helst på en insatsrad',
                    th: '"สัญลักษณ์ที่ตรงกัน 3 ตัวที่ใดๆจะได้รับรางวัลในแถวการจ่าย"',
                    tr: 'Ödeme çizgisinin herhangi bir yerinde açılan\n3 benzer sembol için ödeme yapılır',
                    zh: '"赔付线任意位置上的 3 个同样的符号都可获奖"'
                }
            },
            malfunctionString: {
                styles: {
                    bg: { font: '20px arial' },
                    cs: { font: '20px arial' },
                    da: { font: '20px arial' },
                    de: { font: '20px arial' },
                    el: { font: '18px arial' },
                    en: { font: '20px arial' },
                    es: { font: '20px arial' },
                    et: { font: '20px arial' },
                    fi: { font: '20px arial' },
                    fr: { font: '20px arial' },
                    hu: { font: '18px arial' },
                    is: { font: '20px arial' },
                    it: { font: '20px arial' },
                    ja: { font: '18px arial' },
                    lt: { font: '20px arial' },
                    lv: { font: '20px arial' },
                    nl: { font: '20px arial' },
                    no: { font: '20px arial' },
                    pl: { font: '18px arial' },
                    pt: { font: '20px arial' },
                    ro: { font: '18px arial' },
                    ru: { font: '18px arial' },
                    sk: { font: '18px arial' },
                    sr: { font: '20px arial' },
                    sv: { font: '20px arial' },
                    th: { font: '20px arial' },
                    tr: { font: '18px arial' },
                    zh: { font: '20px arial' }
                },
                value: 'System malfunction voids all pays and all plays',
                translations: {
                    bg: 'Повредите отменят всички плащания и игри',
                    cs: 'Porucha systému nuluje všechny výplaty i všechny hry',
                    da: 'Programfejl gør alle udbetalinger og alle spil ugyldige',
                    de: 'Eine Fehlfunktion macht alle Auszahlungen und Spiele ungültig',
                    el: 'Σε περίπτωση δυσλειτουργίας του συστήματος ακυρώνονται\nόλες οι πληρωμές και τα παιχνίδια',
                    es: 'Un fallo del sistema anula todos los pagos y todas las jugadas',
                    et: 'Süsteemirike tühistab kõik maksed ja mängud',
                    fi: 'Järjestelmän toimintahäiriö mitätöi kaikki maksut ja pelit',
                    fr: 'Un dysfonctionnement du système rend nuls\net non avenus tous les jeux',
                    hu: 'Meghibásodás esetén minden kifizetés és játék érvényét veszti',
                    is: 'Bilun ógildir alla vinninga og leiki',
                    it: 'Un malfunzionamento del sistema annulla\ntutte le vincite e tutte le giocate',
                    ja: 'システムの支障が、全ての支払いとプレイを妨げています',
                    lt: 'Sistemos gedimas panaikina visus mokėjimus ir visus žaidimus',
                    lv: 'Sistēmas kļūmes dēļ tiek atceltas visas izmaksas\nun zaudētas visas spēles.',
                    nl: 'Bij storing vervallen alle uitbetalingen en spellen',
                    no: 'Systemfeil ugyldiggjør alle gevinster og økter',
                    pl: 'Awaria systemu unieważnia wszystkie wypłaty i gry',
                    pt: 'A anomalia de sistema anula todos os ganhos e jogadas',
                    ro: 'Defecțiunea sistemului anulează toate plățile și jocurile',
                    ru: 'Системный сбой может аннулировать игру и выигрыш.',
                    sk: 'Pri poruche systému sú všetky výhry a ťahy neplatné',
                    sr: 'Kvar sistema dovodi do poništenja svih isplata i svih igara',
                    sv: 'Systemfel annullerar alla insatser och spelomgångar',
                    th: 'หากระบบมีความผิดพลาด การจ่ายรางวัลและการเล่นทั้งหมดจะเป็นโมฆะ',
                    tr: 'Sistem hatası meydana gelirse tüm ödemeler ve oyunlar iptal edilir',
                    zh: '系统故障会让所有支付与游戏无效化'
                }
            },
            theoreticalReturnString: {
                value: 'The theoretical return to\nplayer (RTP) for this game is',
                translations : {
                    bg: 'RTP',
                    cs: 'RTP',
                    da: 'RTP',
                    de: 'RTP',
                    el: 'RTP',
                    es: 'RTP',
                    et: 'RTP',
                    fi: 'RTP',
                    fr: 'RTP',
                    hu: 'RTP',
                    is: 'RTP',
                    it: 'RTP',
                    ja: 'RTP',
                    lt: 'RTP',
                    lv: 'RTP',
                    nl: 'RTP',
                    no: 'RTP',
                    pl: 'RTP',
                    pt: 'RTP',
                    ro: 'RTP',
                    ru: 'RTP',
                    sk: 'RTP',
                    sr: 'RTP',
                    sv: 'RTP',
                    th: 'RTP',
                    tr: 'RTP',
                    zh: 'RTP'
                }
            },
            versionString: {
                styles: {
                    bg: { font: '20px arial' },
                    cs: { font: '20px arial' },
                    da: { font: '20px arial' },
                    de: { font: '20px arial' },
                    el: { font: '20px arial' },
                    en: { font: '20px arial' },
                    es: { font: '20px arial' },
                    et: { font: '20px arial' },
                    fi: { font: '20px arial' },
                    fr: { font: '20px arial' },
                    hu: { font: '20px arial' },
                    is: { font: '20px arial' },
                    it: { font: '20px arial' },
                    ja: { font: '20px arial' },
                    lt: { font: '20px arial' },
                    lv: { font: '20px arial' },
                    nl: { font: '20px arial' },
                    no: { font: '20px arial' },
                    pl: { font: '20px arial' },
                    pt: { font: '20px arial' },
                    ro: { font: '20px arial' },
                    ru: { font: '20px arial' },
                    sk: { font: '20px arial' },
                    sr: { font: '20px arial' },
                    sv: { font: '20px arial' },
                    th: { font: '20px arial' },
                    tr: { font: '20px arial' },
                    zh: { font: '20px arial' }
                },
                value: 'V',
                translations : {
                    bg: 'V',
                    cs: 'V',
                    da: 'V',
                    de: 'V',
                    el: 'V',
                    es: 'V',
                    et: 'V',
                    fi: 'V',
                    fr: 'V',
                    hu: 'V',
                    is: 'V',
                    it: 'V',
                    ja: 'V',
                    lt: 'V',
                    lv: 'V',
                    nl: 'V',
                    no: 'V',
                    pl: 'V',
                    pt: 'V',
                    ro: 'V',
                    ru: 'V',
                    sk: 'V',
                    sr: 'V',
                    sv: 'V',
                    th: 'V',
                    tr: 'V',
                    zh: 'V'
                 }
            }
        }
    },
    autoplaySettings : {
        headerString : {
            value : 'Autoplay Settings',
            styles : {
                el : { font : '30px arial' },
                et : { font : '30px arial' },
                fi : { font : '30px arial' },
                lt : { font : '30px arial' },
                lv : { font : '30px arial' },
                nl : { font : '30px arial' },
                pl : { font : '30px arial' },
                pt : { font : '30px arial' },
                sr : { font : '30px arial' },
            },
            translations: {
                bg: 'Настройки на автоиграта',
                cs: 'Nastavení automatické hry',
                da: 'Indstillinger for autospil',
                de: 'Autoplay-Einstellungen',
                el: 'Ρυθμίσεις Αυτόματου Παιχνιδιού',
                es: 'Ajustes de juego automático',
                et: 'Automaatse mängimise seaded',
                fi: 'Automaattisen pelaamisen asetukset',
                fr: 'Paramètres jeu auto',
                hu: 'Automatikus játék beállításai',
                is: 'Sjálfsspilunarstillingar',
                it: 'Impostazioni autoplay',
                ja: 'オートプレイの設定',
                lt: 'Automatinio paleidimo nustatymai',
                lv: 'Automātiskās spēles iestatījumi',
                nl: 'Instellingen voor automatisch spelen',
                no: 'Autospillinnstillinger',
                pl: 'Ustawienia automatycznej gry',
                pt: 'Definições de jogada automática',
                ro: 'Setări joc automat',
                ru: 'Настройки автоигры',
                sk: 'Nastavenia automatickej hry',
                sr: 'Podešavanja za automatsku igru',
                sv: 'Inställningar för autospel',
                th: 'การตั้งค่าการเล่นอัตโนมัติ',
                tr: 'Otomatik Oyun Ayarları',
                zh: '自动游戏设定'
            }
        },
        selectString : {
            value : 'Select',
            translations: {
                bg: 'Избери',
                cs: 'Vybrat',
                da: 'Vælg',
                de: 'Auswählen',
                el: 'Επιλογή',
                es: 'Seleccionar',
                et: 'Vali',
                fi: 'Valitse',
                fr: 'Choisir',
                hu: 'Kiválasztás',
                is: 'Velja',
                it: 'Seleziona',
                ja: '選択',
                lt: 'Pasirinkti',
                lv: 'Izvēlēties',
                nl: 'Selecteren',
                no: 'Velg',
                pl: 'Wybierz',
                pt: 'Selecionar',
                ro: 'Selectare',
                ru: 'Выбрать',
                sk: 'Výber',
                sr: 'Izaberi',
                sv: 'Välj',
                th: 'เลือก',
                tr: 'Seçim',
                zh: '选择'
            }
        },
        unlimitedString : {
            value : 'Unlimited',
            translations: {
                bg: 'Неограничени',
                cs: 'Bez omezení',
                da: 'Ubegrænset',
                de: 'Unbegrenzt',
                el: 'Απεριόριστα',
                es: 'Ilimitado',
                et: 'Piiramatu',
                fi: 'Rajoittamaton',
                fr: 'Illimité',
                hu: 'Korlátlan',
                is: 'Ótakmarkað',
                it: 'Illimitati',
                ja: '無制限',
                lt: 'Neribotas',
                lv: 'Neierobežota',
                nl: 'Onbeperkt',
                no: 'Ubegrenset',
                pl: 'Nieograniczone',
                pt: 'Ilimitado',
                ro: 'Nelimitat',
                ru: 'Неограниченный',
                sk: 'Neobmedzené',
                sr: 'Neograničeno',
                sv: 'Obegränsat',
                th: 'ไม่จำกัด',
                tr: 'Sınırsız',
                zh: '无限制'
            }
        },
        anyString : {
            value : 'Any',
            translations: {
                bg: 'Всички',
                cs: 'Libovolné',
                da: 'Enhver',
                de: 'Beliebig',
                el: 'Οποιαδήποτε',
                es: 'Cualquiera',
                et: 'Ükskõik milline',
                fi: 'Mikä tahansa',
                fr: 'Tous',
                hu: 'Bármely',
                is: 'Allt',
                it: 'Qualunque',
                ja: 'すべて',
                lt: 'Bet kuris',
                lv: 'Jebkuru',
                nl: 'Willekeurig',
                no: 'Hvilken som helst',
                pl: 'Dowolne',
                pt: 'Qualquer',
                ro: 'Oricare',
                ru: 'Любой',
                sk: 'Ľubovoľné',
                sr: 'Bilo koji',
                sv: 'Ett',
                th: 'ค่าใดก็ได้',
                tr: 'Tümü',
                zh: '任意'
            }
        },
        yesString : {
            value : 'Yes',
            translations: {
                bg: 'Да',
                cs: 'Ano',
                da: 'Ja',
                de: 'Ja',
                el: 'Ναι',
                es: 'Sí',
                et: 'Jah',
                fi: 'Kyllä',
                fr: 'Oui',
                hu: 'Igen',
                is: 'Já',
                it: 'Sì',
                ja: 'はい',
                lt: 'Taip',
                lv: 'Jā',
                nl: 'Ja',
                no: 'Ja',
                pl: 'Tak',
                pt: 'Sim',
                ro: 'Da',
                ru: 'Да',
                sk: 'Áno',
                sr: 'Da',
                sv: 'Ja',
                th: 'ใช่',
                tr: 'Evet',
                zh: '是'
            }
        },
        noString : {
            value : 'No',
            translations: {
                bg: 'Не',
                cs: 'Ne',
                da: 'Nej',
                de: 'Nein',
                el: 'Όχι',
                es: 'No',
                et: 'Ei',
                fi: 'Ei',
                fr: 'Non',
                hu: 'Nem',
                is: 'Nei',
                it: 'No',
                ja: 'いいえ',
                lt: 'Ne',
                lv: 'Nē',
                nl: 'Nee',
                no: 'Nei',
                pl: 'Nie',
                pt: 'Não',
                ro: 'Nu',
                ru: 'Нет',
                sk: 'Nie',
                sr: 'Ne',
                sv: 'Nej',
                th: 'ไม่ใช่',
                tr: 'Hayır',
                zh: '否'
            }
        },
        settings : [
            {
                id : 'numberOfRounds',
                type : 'select',
                valueType : 'integer',
                values : [100, 50, 25, 10, 5],
                defaultIndex: null,
                label: {
                    value : 'Number of Plays',
                    translations: {
                        bg: 'Брой игри',
                        cs: 'Počet her',
                        da: 'Antal spil',
                        de: 'Rundenzahl',
                        el: 'Αριθμός Παιχνιδιών',
                        es: 'Número de jugadas',
                        et: 'Mängude arv',
                        fi: 'Pelien määrä',
                        fr: 'Nombre de jeux',
                        hu: 'Játékok száma',
                        is: 'Fjöldi leikja',
                        it: 'Numero di giocate',
                        ja: 'プレイ数',
                        lt: 'Žaidimų kiekis',
                        lv: 'Spēļu skaits',
                        nl: 'Aantal spellen',
                        no: 'Antall økter',
                        pl: 'Liczba gier',
                        pt: 'Número de jogadas',
                        ro: 'Număr de jocuri',
                        ru: 'Количество игр',
                        sk: 'Počet hier',
                        sr: 'Broj igara',
                        sv: 'Antal omgångar',
                        th: 'จำนวนการเล่น',
                        tr: 'Oyun Sayısı',
                        zh: '局数'
                    }
                }
            },
            {
                id : 'lossLimit',
                type : 'select',
                valueType : 'multiplier',
                values : [100, 50, 25, 10, 5, 2, 1],
                defaultIndex : null,
                label : {
                    value : 'Loss Limit',
                    translations: {
                        bg: 'Лимит на загубите',
                        cs: 'Limit na ztráty',
                        da: 'Tabsgrænse',
                        de: 'Verlustgrenze',
                        el: 'Όριο Ήττας',
                        es: 'Límite de pérdidas',
                        et: 'Kaotuse limiit',
                        fi: 'Häviöraja',
                        fr: 'Limite de pertes',
                        hu: 'Veszteségi korlát',
                        is: 'Mörk taps',
                        it: 'Limite perdite',
                        ja: '負けの上限',
                        lt: 'Nuostolio riba',
                        lv: 'Zaudējumu ierobežojums',
                        nl: 'Verlieslimiet',
                        no: 'Tapsgrense',
                        pl: 'Limit straty',
                        pt: 'Limite de perda',
                        ro: 'Limită de pierdere',
                        ru: 'Предел убытков',
                        sk: 'Limit pre prehru',
                        sr: 'Ograničenje za gubitak',
                        sv: 'Förlustgräns',
                        th: 'ขีดจำกัดการเสีย',
                        tr: 'Kayıp Limiti',
                        zh: '损失限制'
                    }
                }
            },
            {
                id : 'singleWinLimit',
                type : 'select',
                valueType : 'multiplier',
                values : ['Unlimited', 500, 200, 100, 50, 25, 20, 15, 10, 5, 2, 1, 'Any'],
                defaultIndex : 0,
                label : {
                    value : 'Single Win Limit',
                    translations: {
                        bg: 'Лимит за единична печалба',
                        cs: 'Limit na jednu výhru',
                        da: 'Grænse for enkeltgevinster',
                        de: 'Gewinngrenze pro Spiel',
                        el: 'Όριο Μεμονωμένης Νίκης',
                        es: 'Límite de ganancia única',
                        et: 'Üksiku võidu limiit',
                        fi: 'Yksittäisen voiton raja',
                        fr: 'Limite de gains uniques',
                        hu: 'Egyszerre maximálisan megnyerhető összeg',
                        is: 'Stök vinningsmörk',
                        it: 'Limite vincita singola',
                        ja: '1回の勝ちの上限',
                        lt: 'Vieno laimėjimo riba',
                        lv: 'Viena laimesta maksimālā summa',
                        nl: 'Limiet voor enkele winst',
                        no: 'Grense for enkeltgevinst',
                        pl: 'Limit pojedynczej wygranej',
                        pt: 'Limite de prémio único',
                        ro: 'Limită câștig unic',
                        ru: 'Предельный выигрыш за одну игру',
                        sk: 'Limit pre samostatnú výhru',
                        sr: 'Ograničenje za jedan dobitak',
                        sv: 'Enkelvinstgräns',
                        th: 'ขีดจำกัดการชนะครั้งเดียว',
                        tr: 'Tek Kazanç Limiti',
                        zh: '单场奖金限制'
                    }
                }
            },
            {
                id : 'haltOnWin',
                type : 'checkbox',
                valueType : null,
                values :[ 'No', 'Yes' ],
                defaultIndex : 0,
                label : {
                    value : 'Halt on Win',
                    translations: {
                        bg: 'Спиране при печалба',
                        cs: 'Zastavení při výhře',
                        da: 'Stop ved gevinst',
                        de: 'Bei Gewinn aufhören',
                        el: 'Διακοπή κατά τη Νίκη',
                        es: 'Parar al ganar',
                        et: 'Peata võidu korral',
                        fi: 'Keskeytä, kun saat voiton',
                        fr: 'Arrêt lors d\'une victoire',
                        hu: 'Leállítás nyeremény esetén',
                        is: 'Stöðva við vinning',
                        it: 'Smetti alla vincita',
                        ja: '勝った時に停止',
                        lt: 'Sustabdyti laimėjimą',
                        lv: 'Apturēt laimesta gadījumā',
                        nl: 'Stop bij winst',
                        no: 'Stans gevinst',
                        pl: 'Zatrzymaj po wygranej',
                        pt: 'Parar ao ganhar',
                        ro: 'Oprire la înregistrarea unui câștig',
                        ru: 'Остановка после выигрыша',
                        sk: 'Zastaviť v prípade výhry',
                        sr: 'Zaustavljanje nakon dobitka',
                        sv: 'Stanna vid vinst',
                        th: 'หยุดเมื่อชนะ',
                        tr: 'Kazanınca Dur',
                        zh: '获胜时停止'
                    }
                }
            }
        ]
    }
};